### ISSUE TITLE
Calendar - rangeFrom

### ISSUE THREAD

**Issue by wojtekhorembala** [nitsnets/unicorn_components#14]
Hi, i want use calendar rangeFrom.
` <uni-calendar [(model)]="daySelected"></uni-calendar>`
I've tried a lot of combinations but I do not want to work, can you give me an example of how to do it?

**Comment by AlvYuste** [comment]
Hello! here you can find an [example](https://nitsnets.github.io/unicorn_components/?selectedKind=Date%20and%20time%2FCalendar&selectedStory=Range%20from&full=0&addons=1&stories=1&panelRight=0) of `rangeFrom` usage ([code](https://github.com/nitsnets/unicorn_components/blob/master/src/components/ui/calendar/calendar.component.demo.ts#L32)). It shoul receive a date in YYYY-MM-DD format and is mean to highlight a range of dates (starting from `rangeFrom` until the date selected).

If you want to use a date range picker, better go with `<uni-daterange-picker>`. You can find more info of that component in its [docs](https://github.com/nitsnets/unicorn_components/tree/master/src/components/forms/daterange-picker) (sadly still in spanish) or [examples](https://nitsnets.github.io/unicorn_components/?selectedKind=Date%20and%20time%2FDate-range%20picker&selectedStory=Basic&full=0&addons=1&stories=1&panelRight=0).
