### ISSUE TITLE
Charts overlap in the demo page

### ISSUE THREAD

**Issue by gimenete** [nitsnets/unicorn_components#4]
<img width="1680" alt="screen shot 2018-01-16 at 12 02 48" src="https://user-images.githubusercontent.com/50486/34985726-5a9687fc-fab5-11e7-9ff2-1b3c67011086.png">

**Comment by AlvYuste** [comment]
Good point @gimenete . We are working on a brand new demo page.

We tried [Storybook](https://github.com/storybooks/storybook) for Angular, but found this issue https://github.com/storybooks/storybook/issues/2778. Many components here have inheritance/extensions so we cannot go with that platform until it is fixed.

The first step wil be placing the demo code at this repo, (i.e at `/demo/` folder) to have it unified and let contributions there also.

**Comment by alebarbaja** [comment]
In my case it looks correct, but only on desktop:

![charts-unicorn-components-desktop](https://user-images.githubusercontent.com/28918805/35149422-483953a6-fd16-11e7-92fd-53fd120c6f33.PNG)

**Comment by AlvYuste** [comment]
If anyone has more experience with Storybook for Angular and figure out a solution, feel free to look at the branch [feature/storybook](https://github.com/nitsnets/unicorn_components/tree/feature/storybook)

**Comment by AlvYuste** [comment]
Finally the new demo is released! Hope you like it 😄 
https://nitsnets.github.io/unicorn_components
The charts will go in the next versions of it.
