### ISSUE TITLE
uni-button-file URL correction

### ISSUE THREAD

**Issue by alebarbaja** [nitsnets/unicorn_components#8]
The documentation of the uni-button-file component leads to the uni-button documentation. However, when I want to edit the README.md, it leads to the correct documentation. Any ideas?

![uni-button-nitsnets](https://user-images.githubusercontent.com/28918805/34987033-1555efe8-faba-11e7-8943-73f1e64a159a.png)

**Comment by AlvYuste** [comment]
I've checked it and seems like the final link was wrong at `line 161`.

It is fixed by https://github.com/nitsnets/unicorn_components/commit/2e198ecf2a462cb7a40274351df687b85e70e803

Thanks for the point!
